// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe-ilvO-owr0ffW8LEcIm2Q51F7b0r08c',
    appId: '1:802545946373:web:b71a237409113a0690f16c',
    messagingSenderId: '802545946373',
    projectId: 'dalel-f12b0',
    authDomain: 'dalel-f12b0.firebaseapp.com',
    storageBucket: 'dalel-f12b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtnOujSk6cqY53PjJ_szyJLUv0wm1csT8',
    appId: '1:802545946373:android:9f23c36f5347635390f16c',
    messagingSenderId: '802545946373',
    projectId: 'dalel-f12b0',
    storageBucket: 'dalel-f12b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaXiA-lXIxqLm6Qf_91Ua6tOemJq77MNQ',
    appId: '1:802545946373:ios:fcfe7e6b80dbfb3190f16c',
    messagingSenderId: '802545946373',
    projectId: 'dalel-f12b0',
    storageBucket: 'dalel-f12b0.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaXiA-lXIxqLm6Qf_91Ua6tOemJq77MNQ',
    appId: '1:802545946373:ios:fcfe7e6b80dbfb3190f16c',
    messagingSenderId: '802545946373',
    projectId: 'dalel-f12b0',
    storageBucket: 'dalel-f12b0.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe-ilvO-owr0ffW8LEcIm2Q51F7b0r08c',
    appId: '1:802545946373:web:017fa1c4d61049d190f16c',
    messagingSenderId: '802545946373',
    projectId: 'dalel-f12b0',
    authDomain: 'dalel-f12b0.firebaseapp.com',
    storageBucket: 'dalel-f12b0.appspot.com',
  );
}
